package com_automation

// list import classes
import com.iotbpm.model.StateList;
import com.iotbpm.model.DeviceEvent;

// default dialect for the semantic code will be MVEL
dialect "mvel"

// 100111 - Arduino Tron IoT

rule "processID rule for device ID: 100222 - Temperature-Humidity"
	when
		$event : DeviceEvent( $eventId : id, $eventId == "100222" )
	then
	//	com.iotbpm.model.StateList.getInstance().putState("processID", "com.Temperature");
end
